package com.cve.web.db;

import com.cve.db.DBResultSet;
import com.cve.db.SQL;
import com.cve.util.AnnotatedStackTrace;
import com.cve.util.Check;
import com.cve.web.Model;
import javax.annotation.concurrent.Immutable;

/**
 * Logical representation of a bare SQL page.
 * @author Curt
 */
@Immutable
final class FreeFormQueryModel implements Model {

    /**
     * The select used to generate the results.
     */
    public final SQL sql;

    /**
     * The results generated by the SQL.
     */
    public final DBResultSet results;

    /**
     * Feedback to the user like an error message.
     */
    public final String message;

    /**
     * All that we know about what went wrong, or null if everything is OK.
     */
    public final AnnotatedStackTrace trace;

    /**
     * Literals to use in the form.
     */
    static final String Q  = "q";

    FreeFormQueryModel(SQL sql, DBResultSet results, String message, AnnotatedStackTrace trace) {
        this.sql     = Check.notNull(sql);
        this.results = Check.notNull(results);
        this.message = Check.notNull(message);
        this.trace   = trace;
    }
}
