package com.cve.web.db;

import com.cve.db.DBResultSet;
import com.cve.db.SQL;
import com.cve.util.Check;
import com.cve.web.Model;
import javax.annotation.concurrent.Immutable;

/**
 * Logical representation of a bare SQL page.
 * @author Curt
 */
@Immutable
final class SQLModel implements Model {

    /**
     * The select used to generate the results.
     */
    public final SQL sql;

    /**
     * The results generated by the SQL.
     */
    public final DBResultSet results;

    SQLModel(SQL sql, DBResultSet results) {
        this.sql = Check.notNull(sql);
        this.results = Check.notNull(results);
    }
}
